language: node_js
node_js:
  - "12.13.0"
install:
  - npm install
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - redis-tools
services:
  - redis-server
script: echo PING | nc localhost 6379